### ISSUE TITLE
because the rajce upgrade cant be use 

### ISSUE THREAD

**Issue by zssnode** [CoolmanCZ/rajce#1]
because the rajce upgrade cant be use, and the rajce https(ssl) are not support in chrome，hope  you can change https to http

**Comment by CoolmanCZ** [comment]
Hi,

Try latest 1.2.2 version

**Comment by zssnode** [comment]
great ! thank you ! one more issue， if  the album is update new pics , and i donwload ,it will download all album over again,  any solution can skip already exists pics？

**Comment by zssnode** [comment]
software menu is too big for me , if the http proxy option put in to other menu (Drop-down or next page)， that will be perfect



sorry for ask too many request

**Comment by CoolmanCZ** [comment]
Hi,

New issues are created #2 and #3, this issue is fixed by 2478b0e

BR, Radek
