### ISSUE TITLE
Downloading albums that contain special characters results in empty folders

### ISSUE THREAD

**Issue by MikulasZelinka** [CoolmanCZ/rajce#10]
Setting `Adresa alba` to `http://user.rajce.idnes.cz/album_name...` and then starting the download results in the photos being downloaded but the resulting folder being empty. Does not happen without the `...` in the URL.

Specifying a folder manually doesn't help as a subfolder with name `album_name` gets created automatically but (probably since there is a mismatch between the URL and the album name) the folder is empty upon download finish.

**Comment by CoolmanCZ** [comment]
Hi,
Try the 1.4.2 version.
BR, Radek

**Comment by MikulasZelinka** [comment]
Thanks, works now :)

**Comment by CoolmanCZ** [comment]
You are welcome.
