### ISSUE TITLE
Video files download not work

### ISSUE THREAD

**Issue by Lenushta** [CoolmanCZ/rajce#14]
I have version v1.5.16 but videos download not work. I have checked "Stahovat video soubory" but it download only photos.

**Comment by CoolmanCZ** [comment]
Thank you for reporting an error. I'll look into it as soon as possible.

**Comment by CoolmanCZ** [comment]
Hi, may I ask to explain your problem a little more detail? E.g. operating system and a link to the album, where you found the problem? I've checked my test album https://coolmancz.rajce.idnes.cz/test/ and 1.5.16 works fine. The video was downloaded.

**Comment by Lenushta** [comment]
It looks like problem is only with 32bit version. I downloaded 64bit version and it works.
