### ISSUE TITLE
saved in the first folder

### ISSUE THREAD

**Issue by jarpel2** [CoolmanCZ/rajce#16]
Recently this does not happen to my downloads and all are just saved flat in the first folder I chose.
I think there is some change from Rajce that modified the way for resolving the name and album by application. Thx

**Comment by CoolmanCZ** [comment]
Hi,
Thank you for your comment, but may I ask you to be more specific? It is not clear to me where is the problem.

**Comment by jarpel2** [comment]
Dobrý den, 

Můžu asi česky?

Jde o to, že dříve se (pokud bylo zaškrtnuto „ Připojit jméno vlastníka…“) vytvořil nový adresář podle jména a pak podadresář podle alba a následně do toho se uložily soubory.

Nyní se nevytvoří adresáře a všechny soubory se uloží do hlavního adresáře, který je specifikován v aplikaci ve třetím řádku.

Snad je to pochopitelné 😉

 

Díky

**Comment by CoolmanCZ** [comment]
Dobrý den, vyzkoušejte poslední verzi 1.5.17, jestli tato oprava řeší váš problém.

**Comment by jarpel2** [comment]
Děkuji, super

 

Hezký večer
