### ISSUE TITLE
An empty directory with no images since the last update

### ISSUE THREAD

**Issue by tux-86** [CoolmanCZ/rajce#17]
With version 1.5.17, it is not possible save pictures to directory named by album, but the result is an empty directory inside another directory.

**Comment by CoolmanCZ** [comment]
Hi, may I ask you to provide more details, to be able to create a test case?

**Comment by jz-vadium** [comment]
Same problem as tux-86
Something wrong with creating diorectory by name of user and album name...

**Comment by CoolmanCZ** [comment]
Hi, may I ask you to provide more details, to be able to create a test case?

**Comment by jz-74** [comment]
u can try download for example https://7495.rajce.idnes.cz/skryte
it create directory "skryt" with subdirectory "u00e9"

**Comment by jz-74** [comment]
and don't creating directory with name of user ....

**Comment by CoolmanCZ** [comment]
Can you test v1.5.18 release?

**Comment by jz-74** [comment]
1.5.18 is creating good dirwectory for name of album
not crating directory in structure:
{PATH}/name_of_user/name_of_album/

**Comment by CoolmanCZ** [comment]
I see. It works, but user name is prepend only when authorization is enabled. In other cases, it doesn't make sense. Can you check it? I'll provide a new version where the append user name option will be accessible only if authorization is turned on.
