### ISSUE TITLE
Video downloaded only as a JPG preview

### ISSUE THREAD

**Issue by JanKMinar** [CoolmanCZ/rajce#5]
If a downloaded album contains a video, the application downloads only its JPG preview. Is there an option to download the target video, please?

**Comment by CoolmanCZ** [comment]
Hi,
This option is not available yet.
BR, Radek

**Comment by JanKMinar** [comment]
Hi Radek
The application is just great and I enjoy it indeed; many thanks for it. 
Would be better to describe the application rather as "Rajce album downloader - Ultimate++ application to retrieve images and preview icons of videos from the www.rajce.net" than as "Rajce album downloader - Ultimate++ application to retrieve images/videos from the www.rajce.net" ?
Regards
Jan

**Comment by CoolmanCZ** [comment]
Hi Jan,
It is not necessary to update the description. Version 1.3.0 has the option for video download.
BR, Radek
