### ISSUE TITLE
Downloaded videos do not have their full name and miss their file extension

### ISSUE THREAD

**Issue by JanKMinar** [CoolmanCZ/rajce#6]
Hi Radek,
I appreciate your quick response with the update 1.3.0 that downloads videos; many thanks for this.
I have successfully downloaded a video with more words in its name separated by underscore character. However, the downloaded file contained only the first word of the original file name and missed its file extension "mov".
Best regards
Jan

**Comment by CoolmanCZ** [comment]
Hi Jan,
Is your album protected? Is it possible to send me the link to the album? I can provide an e-mail address to you.
BR, Radek

**Comment by CoolmanCZ** [comment]
Hi,
Thank you for the provided link. I found the problem - spaces in the name. The underscores shouldn't be a problem. Can you test [v1.3.1](https://www.malcic.cz/files/rajce-1.3.1-32bit.zip) windows 32bit binary?
BR, Radek

**Comment by JanKMinar** [comment]
I can't believe. So fast and so great! I am just delighted.
Best regards
Jan
