### ISSUE TITLE
video download is broken

### ISSUE THREAD

**Issue by martinveverka** [CoolmanCZ/rajce#8]
zdravím,
píšu za rajče - nedávno jsme vyměnili video přehrávač; url videí jsou nyní přímo dostupné v js objektu photos, takže by úprava neměla být příliš náročná; `videoxml.php` už je nadobro pryč; postupně se těch kostlivců zbavujeme.
mv

**Comment by CoolmanCZ** [comment]
New release 1.4.0 fixed the issue.
