### ISSUE TITLE
Při vložení nové adresy alba se stahují znovu fotografie z předchozích stahování alb

### ISSUE THREAD

**Issue by vithotarek** [CoolmanCZ/rajce#9]
Dobrý den přeji,

snažím se stáhnout alba z Rajčete a stává se mi tento problém, jehož scénář Vám popíši:

[Nastavení]
[X] Povolit uživatelskou autorizaci
[X] Stahovat pouze nové soubory
[X] Připojit jméno vlastníka.....
[X] Použít HTTPS.....

1. Spustím program
2. Vyplním Uživatelské jméno a heslo
3. Vložím URL1 alba (má 10 fotografií)
4. Kliknu Stáhnout.
5. Stáhne se 10 fotografií.
6. Vložím URL2 alba (má 5 fotografií)
7. Kliknu Stáhnout.

8. A zde pozor - nestáhne se 5, ale již 15 fotografií, jak z URL1, tak z URL2,
   patrně se nevyčistí seznam stahovaných URL.

Jedinou pomocí je program restartovat.
Mám verzi https://github.com/CoolmanCZ/rajce/blob/master/release/rajce-1.4.0-64bit.zip, běžím na Windows 10.

Je možné, že dělám něco špatně?

Mockrát děkuji za případnou informaci či fix :-)

Vít Hotárek

**Comment by CoolmanCZ** [comment]
Děkuji za nalezní chyby. Opraveno ve verzi 1.4.1

bug is fixed - clear download list when new URL is set.

**Comment by vithotarek** [comment]
Dobrý den přeji,

děkuji za promptní fix, odpoledne hned vyzkouším.

S pozdravem
Vít Hotárek

______________________________________________________________
